-- main File cunt fuck
local DiscordLib = loadstring(game:HttpGet"https://raw.githubusercontent.com/dawid-scripts/UI-Libs/main/discord%20lib.txt")()
local Notification = loadstring(game:HttpGet("https://raw.githubusercontent.com/Jxereas/UI-Libraries/main/notification_gui_library.lua", true))()
local win = DiscordLib:Window("Flame Hub 1.0")

local serv = win:Server("Flame Hub", "")
local flame = win:Server("Updates", "")
local xd = flame:Channel("1.0") 
xd:Label("FlameHub Scripts:")
xd:Label("- Aimlock Script")
xd:Label("- Hitbox Script")
xd:Label("- Midnight Racing: Tokyo Script")
xd:Label("- Anti-Lag Script")
local aimlock = serv:Channel("Aimlock")
local hitbox = serv:Channel("Hitbox")
local mid = serv:Channel("Midnight Racing: Tokyo")
local dodo = serv:Channel("Anti-Lag")
 
aimlock:Button("Aimlock Script", function()
DiscordLib:Notification("Notification", "Injected Aimlock Script Successfully.", "Okay!")
wait(2.5)
loadstring(game:HttpGet("https://raw.githubusercontent.com/robloxscriptleaks/FHX/main/a.lua"))()
end) 

hitbox:Button("Hitbox Script", function()
DiscordLib:Notification("Notification", "Injected Hitbox Expander Script Successfully.", "Okay!")
wait(2.5)
loadstring(game:HttpGet("https://raw.githubusercontent.com/robloxscriptleaks/FHX/main/c.lua", true))()
end)

mid:Label("password is godxnation")
mid:Button("Click me to copy key", function() 
setclipboard("godxnation")
DiscordLib:Notification("Notification", "Sucessfully set key to clipboard.", "Great!")
end)
mid:Button("Midnight Racing: Tokyo Script", function()
DiscordLib:Notification("Notification", "Injected Midnight Racing: Tokyo Script Successfully.", "Okay!")   
wait(2.5)
loadstring(game:HttpGet("https://raw.githubusercontent.com/GodXNation/GodXNation/main/midnight%20racing%20hubV2%20fixed", true))()
wait(1)
Notification.new("warning", "Warning", "This script may get you banned, use at your own risk.")
end)

dodo:Button("Anti-Lag Script", function()
DiscordLib:Notification("Notification", "Injected Anti-Lag Script Successfully.", "Okay!")   
wait(2.5)
loadstring(game:HttpGet("https://pastebin.com/raw/9ape5um4", true))()
wait(1)
Notification.new("success", "Success", "Anti-Lag Settings Loaded Successfully!")
end)
